services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_url
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: url_db
      MARIADB_USER: explorer
      MARIADB_PASSWORD: explorerpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_url
    ports:
      - "8080:8080"
    environment:
      MARIADB_URI: explorer:explorerpassword@tcp(mariadb:3306)/url_db?charset=utf8mb4&parseTime=True&loc=Local
      BASE_URL: http://localhost:8080
    depends_on:
      - mariadb

  frontend:
    build: ./gourl
    container_name: frontend_url
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  mariadb_data:
