services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_url
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: url_db
      MARIADB_USER: explorer
      MARIADB_PASSWORD: explorerpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
